name: Publish Release

on:
  push:
    branches:
      - master  # Updated to trigger on the `master` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' for JDK 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and Publish
        run: ./gradlew clean build publishReleasePublicationToMavenRepository

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.sha }}"
          release_name: "Release v${{ github.sha }}"
          draft: false
          prerelease: false

      - name: Upload AAR file
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./commons/build/outputs/aar/commons-release.aar  # Updated path for `commons` module
          asset_name: commons-release.aar
          asset_content_type: application/zip
